# Generated by Django 5.0.6 on 2024-05-25 20:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_customuser_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mall',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.city'),
        ),
    ]
