# Generated by Django 5.0.6 on 2024-05-26 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_customuser_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='mall',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='user_photos/'),
        ),
    ]
