# Generated by Django 5.0.6 on 2024-05-26 18:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_mall_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='photo',
        ),
        migrations.RemoveField(
            model_name='mall',
            name='image',
        ),
    ]
